---
title: "R Notebook"
output: html_notebook
---
## I. 분석프레임워크

### 1. 분석 프레임워크
* Set the objective of Analaysis
* Set Hypothesys
* Set Variables 
* Set Analysis method
* Develop analysis data collection
* Analyze
* Interprete

### 2. 분석목표설정
* 내가 궁금한것은 무엇인가? 
- 상품수와 예약수의 관련성 검증.

### 3. 가설수립
- 가설: 상품수가 늘어나면 예약수가 늘어날 것 이다.

### 4. 변수 및 분석방법 선정 (어떤변수일때는 무슨 방법을 써야한다.)
- 측정변수: 상품수, 예약수
- 분석방법: 회귀분석
- 독립변수 (원인)와,종속변수 (결과) : 하지만 원인/결과라고 하지 않음
- 왜냐하면 상관관계와 인과관계가 같지 않음
- 비교하려는 집단 / 비교하려는 값

### 5. 측정도구 개발 (데이터가 없다면..)
- 서베이 구성

### 6. 데이터 수집
- 누구를 대상으로 어떻게 수집할 것 인가(대상, 방법, 수집처)

### 7.통계분석 및 결과해석



## II. 실습

## III. 통계학방법 

- 독립과 종속변수가 명목인지 연속인지에 따라 어떤분석을 써야하는지 판단한다.

* 명목변수 : factor var
* 연속변수 : continous var (숫자의 크기)



### 1) 집단비교하기 - 두집단의 % 를 비교하겠다.

- 카이검증 (두집단의 비율을 비교) : 종속과 독립변수가 모두 명목변수 일때 사용

* 여행지별 사람의 연봉이 더 높을것이다. (연봉 3000이하, 이상)
* 아시아를 여행하는 사람들
* 유럽을 여행하는 사람들

- 카이검증 적용이 가능

* 논리적으로 말이 되어야, 데이터도 수집이 가능


### 2) 집단 평균 비교 - 명목값이 아니라 수치를 비교하겠다.

- T 테스트 (두집단의 평균 비교) : 독립변수는 명목, 종속변수는 연속값

* 표준편차가 커질수록 평균에서 어느정도 떨어져있는지 알려줌
- T값은 집단간 차이가 커질수록 커지는데, T값에 대한 확률치를 P값으로..

* 아시아를 여행하는 사람들
* 유럽을 여행하는 사람들
* 유럽지역여행자의 여행예산 평균이 아시아지역 여행자의 여행예산 평균보다 높을것이다.


### 3) 변수간의 관계 

- 회귀분석

* 독립/종속 변수가 둘다 연속변수
* 광고비가 증가할수록 예약수가 증가할것이다.


- 최소 30개, 무응답 제거하고 100개 ~ 150개.
- 실무 200, 논문 400
- 데이터가 많을수록 좋은건 아님
- 하지만 100개 이상부터는 그 수가 달라지진 않음
- 사례수가 많을수록 p 밸류는 작아진다
- p밸류 외에 다른것들도 봐야한다...

### 기타
- 아노바 - 다중변량분석
- 로지스틱회귀분석 - 독립이 연속 종속이 명목

